/* 沉淀协议：一份正文，按各家 agent 的机制包装成不同文件。
   改内容只改 protocolBody，其它函数只负责套壳。 */

export const MARK_BEGIN = '<!-- personal-kb:begin -->';
export const MARK_END = '<!-- personal-kb:end -->';
/** 只有带这行的文件才敢被插件重写，用户手写的同名文件一律跳过。 */
export const GENERATED_MARK = '<!-- personal-kb:generated -->';

const DESCRIPTION =
  '把对话里可复用的结论沉淀成 Markdown 卡片。用户表达出「这次的结论值得留下来」的意思时' +
  '就使用——「沉淀本次」「记到知识库」「这条值得留」「存成卡片」「以后还会用到」等等，' +
  '按意图判断，不要求逐字匹配。任务收尾出现可复用洞察时主动提议。确认后才写文件。';

export function protocolBody(kbRoot: string): string {
  return `## 什么时候沉淀

**按意图判断，不要逐字匹配。** 用户表达出「这次的结论值得留下来」的意思就执行沉淀，
不管他用的是哪种说法。下面是同一个意图的常见说法，是例子不是白名单：

- 沉淀本次 / 沉淀一下 / 把这个沉淀下来
- 记到知识库 / 记一下这个 / 存下来 / 存成卡片 / 收进卡片 / 入库
- 这条值得留 / 这个别忘了 / 以后还会用到 / 下次别再踩这个坑
- 总结成卡片 / 归档一下 / 加进我的库
- save this / remember this / add to my kb / note this down

用户只说「记一下」「存一下」而上下文里有明确结论时，也算。
真分不清他是要沉淀还是要你改文件，问一句再动手。

任务收尾时如果本轮出现了可复用的思考、方法、idea、易错点、术语口径，主动提议沉淀。
纯执行类的活（改代码、改文案、跑命令）不要提议。

## 怎么沉淀

1. 从本轮提炼 1–3 张候选卡片，每张只讲一个观点。
2. 先把候选报给用户：标题、类型、一句话结论。**用户确认后才写文件。**
3. 确认后写到 \`${kbRoot}/<类型目录>/<文件名>.md\`，文件名用小写英文短横线。
4. 写完在 \`${kbRoot}/INDEX.md\` 里加一行：\`- [标题](类型目录/文件名.md) — 类型 | 一句话钩子\`。
5. 同一主题已有卡片就更新它，不要新开一篇。
6. 不要存 token、密码、密钥、个人信息、一次性任务细节。

## 类型与目录

| type | 目录 | 放什么 |
|------|------|--------|
| thinking | \`thinking/\` | 判断、原则、取舍 |
| fundamentals | \`fundamentals/\` | 可复用的方法、框架、基本功 |
| idea | \`ideas/\` | 还没做成需求的想法 |
| pitfall | \`pitfalls/\` | 易错点、反例，填 \`review_after\`（默认 +30 天） |
| life | \`life/\` | 人生、职业建议 |
| glossary | \`glossary/\` | 术语、黑话、指标口径 |

## 卡片格式

小节标题必须一字不差，阅读端是按 \`## 结论\` 这样的行来解析的。

\`\`\`markdown
---
title: 与正文一级标题一致
type: thinking
tags: [标签1, 标签2]
created: YYYY-MM-DD
source: 哪次对话或哪份材料
review_after:
---

# 与 title 一致

## 结论

一句话说清这张卡片要记住什么。

## 为什么重要

## 怎么用

## 反例 / 易错点

## 来源
\`\`\`

有几段写几段，写不出来的小节可以省掉，但 \`## 结论\` 必须有。
一篇一个观点，尽量一屏读完。不要写「Last updated」「Generated by」这类元数据。

## 先查再答

回答前先读 \`${kbRoot}/INDEX.md\`，命中相关卡片就以卡片为事实来源，不要复述全文。
不要一次把所有卡片读进上下文。索引为空就正常回答。`;
}

/** Comate / Claude Code 这类有独立 skill 目录的，写一份完整 SKILL.md。 */
export function skillFile(kbRoot: string): string {
  return `---
name: personal-kb
description: ${DESCRIPTION}
---

${GENERATED_MARK}

# 个人知识库 personal-kb

卡片都存在 \`${kbRoot}\`，由 VS Code 插件 Personal KB 卡片墙负责展示。
这个文件由插件生成，删掉上面那行注释它就不会再被覆盖。

${protocolBody(kbRoot)}
`;
}

/** Cursor 的项目/全局规则文件。 */
export function cursorRule(kbRoot: string): string {
  return `---
description: ${DESCRIPTION}
alwaysApply: true
---

${GENERATED_MARK}

# 沉淀卡片到 Personal KB

${protocolBody(kbRoot)}
`;
}

/** Codex 的 AGENTS.md 这类共享文件，只能追加带标记的块。 */
export function markedBlock(kbRoot: string): string {
  return `${MARK_BEGIN}
# 沉淀卡片到 Personal KB

${protocolBody(kbRoot)}
${MARK_END}`;
}

/** 把标记块写进一段已有文本：已有就替换，没有就追加。标记外的内容不动。 */
export function upsertBlock(existing: string, block: string): string {
  const from = existing.indexOf(MARK_BEGIN);
  const to = existing.indexOf(MARK_END);
  if (from !== -1 && to !== -1 && to > from) {
    return existing.slice(0, from) + block + existing.slice(to + MARK_END.length);
  }
  const base = existing.trimEnd();
  return base ? `${base}\n\n${block}\n` : `${block}\n`;
}

/** 摘掉标记块，标记外的内容一个字不动。 */
export function removeBlock(existing: string): string {
  const from = existing.indexOf(MARK_BEGIN);
  const to = existing.indexOf(MARK_END);
  if (from === -1 || to === -1 || to < from) {
    return existing;
  }
  const out = existing.slice(0, from).trimEnd() + '\n' + existing.slice(to + MARK_END.length).trimStart();
  return out.trim() ? out : '';
}
